# This is a basic workflow to Test HiCUP

name: HiCUP_Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, development, actions ]
  pull_request:
    branches: [ master, development, actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Update Ubuntu
      run: |
        sudo apt-get update 

    - name: Install dependencies
      run: |
        sudo apt install samtools
        sudo apt install bowtie2
        sudo apt install r-base-core
        sudo apt install bioperl

    - name: Test all perl scripts
      run: |
        $GITHUB_WORKSPACE/hicup --help
        $GITHUB_WORKSPACE/hicup --version
        $GITHUB_WORKSPACE/hicup_mapper --help
        $GITHUB_WORKSPACE/hicup_digester --help
        $GITHUB_WORKSPACE/hicup_truncater --help
        $GITHUB_WORKSPACE/hicup_deduplicator 2>&1 | grep Please
        $GITHUB_WORKSPACE/Conversion/hicup2hicpipe --help
        $GITHUB_WORKSPACE/Conversion/hicup2gothic --help
        $GITHUB_WORKSPACE/Conversion/hicup2fithic --help
        $GITHUB_WORKSPACE/Conversion/hicup2homer --help
        $GITHUB_WORKSPACE/Conversion/hicup2juicer --help
        $GITHUB_WORKSPACE/Conversion/hicup2ncc --help
        $GITHUB_WORKSPACE/Misc/find_common_fragment_interactions.pl --help || [[ $? == 255 ]]
        $GITHUB_WORKSPACE/Misc/hicup_capture --help
        $GITHUB_WORKSPACE/Misc/make_hic_array.pl || [[ $? == 255 ]]
        $GITHUB_WORKSPACE/scribler/scribler --help
        $GITHUB_WORKSPACE/scribler/scribl_capture_ditag_sorter.pl || [[ $? == 255 ]]
        $GITHUB_WORKSPACE/scribler/scribl_capture.pl || [[ $? == 255 ]]
        $GITHUB_WORKSPACE/scribler/scribl_capture_region_breakdown.pl || [[ $? == 255 ]]
                         
    - name: Download Test Dataset and FASTA files
      run: |
        wget -nv https://www.bioinformatics.babraham.ac.uk/projects/hicup/test_dataset.tar.gz
        tar xvzf test_dataset.tar.gz
        wget -nv https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr21.fa.gz
        wget -nv https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz
        cat chr*.fa.gz | gunzip > chr21chr22_hg38.fa

    - name: Build bowtie2 index
      run: |
        mkdir -p chr21chr22_hg38
        bowtie2-build chr21chr22_hg38.fa chr21chr22_hg38/chr21chr22_hg38
        
    - name: Run HiCUP
      run: |
        $GITHUB_WORKSPACE/hicup_digester --re1 A^AGCTT,HindIII --genome Human38chr21and22 --zip chr21chr22_hg38.fa
        $GITHUB_WORKSPACE/hicup --bowtie2 $(which bowtie2) --digest Digest* --zip --threads 2 --index ./chr21chr22_hg38/chr21chr22_hg38 --shortest 50 --longest 700 test_dataset/*.fastq
        
    - name: Check results
      run: |
         $GITHUB_WORKSPACE/Testing/hicup_checker --threshold 5 --expected $GITHUB_WORKSPACE/Testing/test_output/HiCUP_summary_report_lHWLvpbSoZ_13-54-49_16-02-2023.txt --new HiCUP_summary_report_* 

    - name: Run hicup2juicer
      run: |
        $GITHUB_WORKSPACE/Conversion/hicup2juicer --nosort --usemid --digest Digest_Human38chr21and22_HindIII_None_*txt.gz test_dataset1_2.hicup.bam
        mv test_dataset1_2.hicup.bam.prejuicer nosortusemid.prejuicer
        $GITHUB_WORKSPACE/Conversion/hicup2juicer --useindex test_dataset1_2.hicup.bam
        mv test_dataset1_2.hicup.bam.prejuicer useindex.prejuicer


    - name: Check results
      run: |
          echo "Testing nosort usemid"
          n_lines_diff=$(diff nosortusemid.prejuicer $GITHUB_WORKSPACE/Testing/test_output/test_dataset1_2.hicup.bam.prejuicer | wc -l)
          if [ $n_lines_diff -neq 0 ]; then
            echo "Files are different"
            diff  nosortusemid.prejuicer $GITHUB_WORKSPACE/Testing/test_output/test_dataset1_2.hicup.bam.prejuicer
            exit 1
          else
            echo "Files are identical"
          fi
          echo "Testing useindex"
          n_lines_diff=$(diff useindex.prejuicer $GITHUB_WORKSPACE/Testing/test_output/test_dataset1_2.hicup.bam.prejuicer2 | wc -l)
          if [ $n_lines_diff -neq 0 ]; then
            echo "Files are different"
            diff useindex.prejuicer $GITHUB_WORKSPACE/Testing/test_output/test_dataset1_2.hicup.bam.prejuicer2
            exit 1
          else
            echo "Files are identical"
          fi
        